version: 2.1

jobs:
  install:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - test
