version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0
    working_directory: ~/repo
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      
      # Step 2: create virtual environment and install dependencies
      - run:
          name: install dependencies
          command: |
            npm ci

      # Optional: Store test results
      - store_test_results:
          path: test-results

      # Optional: Store artifacts like coverage reports
      - store_artifacts:
          path: coverage
          destination: coverage-report

workflows:
  version: 2
  build-and-test:
    jobs:
      - build